# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../_base
  
patches:
- path: patch-memory.yaml
- path: patch-replicas.yaml
- path: patch-service.yaml
