apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook 
  annotations:
  namespace: argocd  
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 5
  syncPolicy:
    automated:
      prune: true
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/hungtran84/argocd-example-app.git
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
