kubectl apply -f backend-secret.yaml
kubectl apply -f backend-service.yaml
kubectl apply -f backend.yaml
kubectl apply -f frontend-configmap.yaml
kubectl apply -f frontend-service.yaml
kubectl apply -f frontend.yaml
kubectl apply -f ingress.yaml
kubectl apply -f mongodb-persistent-volume.yaml
kubectl apply -f mongodb-persistent-volume-claim.yaml
kubectl apply -f mongodb-secret.yaml
kubectl apply -f mongodb-service.yaml
kubectl apply -f mongodb.yaml
