apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/todo
  - namespace.yaml
components:
  - ../../components/mysql
  - ../../components/common-labels
  - ../../components/security-context
  - ../../components/ingress
namespace: prod
labels:
  - pairs:
      app.kubernetes.io/env: prod
buildMetadata:
  - managedByLabel
  - originAnnotations
