apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-lab
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: helm-guestbook
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/hungtran84/argocd-example-app.git
