apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ingress.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
    target:
      kind: Service
      name: todo
