apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/securityContext
    target:
      kind: Deployment
      name: todo
