# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add the desired Prefix to all resources
namePrefix: prefix-tokp01-
nameSuffix: -suffix-tokp01

resources:
  - ../_base
